language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services: mysql

env: TRAVIS=1

matrix:
  allow_failures:
    - php: hhvm
  fast-finish: true

before_script:
  # Get Composer Up and Running
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - travis_retry composer dump-autoload -o
  # Create the database and set a different root password
  - mysql -e 'create database IF NOT EXISTS sprint;' -uroot
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  # Get APACHE setup and running
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

script:
  - php index.php database quietMigrate
  - php codecept.phar run --env travis

after_failure:
  - cat tests/_output/*